#!/usr/bin/python3

import os
import sys

venv_python = "/opt/docsearch/venv/bin/python"

if sys.executable != venv_python:
    os.execv(
        venv_python,
        [venv_python] + sys.argv
    )

import main

